### ISSUE TITLE
Issue to construct DOTA dataset

### ISSUE THREAD

**Issue by TerrafYassin** [ZhAnGToNG1/MSFC-Net#1]
Thank you for your good work, I want to know please how can I have a DOTA dataset using the data augmentation methods used in your paper , I  found 2608 images on the official site DOTA but you have 54,500 images in your paper;
if you have any code how we can increase the dataset or   upload it into  drive or ondrive link.
Thanks.

**Comment by ZhAnGToNG1** [comment]
- Please follow the [https://github.com/ZhAnGToNG1/MSFC-Net/blob/master/README.md](url) : **Prepare dataset** to construct DOTA dataset.
- About how to increase the dataset : You can refer to the code https://github.com/ZhAnGToNG1/MSFC-Net/blob/master/dota_dekit/ImgSplit_multi_process.py#L295 .  Changing the parameter of **split.splitdata()** to 1.2, 1.0 and 0.4. (i.e., resizing the original training set of DOTA into multiple scales, ×1.2, ×1, and ×0.4, and crop them into 512 × 512 subimages respectively, where each 512 × 512 training image has a 200-pixel overlap.)

**Comment by TerrafYassin** [comment]
Thank you.
