### ISSUE TITLE
didn't receive best_model ?

### ISSUE THREAD

**Issue by Ismaildata** [ZhAnGToNG1/MSFC-Net#10]
please , When i finish training my model i didn't received best_model.pth i received just last_model.pth , what is the problem could be ?

**Comment by ZhAnGToNG1** [comment]
Please read carefully the code [https://github.com/ZhAnGToNG1/MSFC-Net/blob/master/src/train.py#L84](url)

**Comment by Ismaildata** [comment]
please what is opt.val_intervals and what values it accept ?

**Comment by ZhAnGToNG1** [comment]
See https://github.com/ZhAnGToNG1/MSFC-Net/blob/master/src/lib/opts.py#L91

**Comment by Ismaildata** [comment]
please to test mAP of my model ; there is a mismatch between ground-truth and detection results format : 
for ground-truth : classe_index  coordinates  .
for detection results : class_name coordines .
i receive mAP of 0.00  
please how can i solve this issue .

**Comment by ZhAnGToNG1** [comment]
Before using the [https://github.com/Cartucho/mAP](url) to calculating the mAP (please refer to its usage), 

- prepare the ground-truth of your own dataset (like [https://github.com/ZhAnGToNG1/MSFC-Net/tree/master/exp/mAP/DOTA/input/ground-truth](url) )  (its format: class_name x1 y1 x2 y2)  , then put them in **MSFC-Net_ROOT/exp/mAP/DOTA(DIOR)/input/ground-truth/**
- Get the detection results from testing code (its format: class_name score x1 y1 x2 y2) , then put them in **MSFC-Net_ROOT/exp/mAP/DOTA(DIOR)/input/detection-results/**
- Then, refer to [https://github.com/ZhAnGToNG1/MSFC-Net/blob/master/README.md](url) **Evaluation** to calculate mAP. (Please make sure the format is correct)

**Comment by Ismaildata** [comment]
Yes , but my question there is no function to transfer ground truth format from class_index x1 y1 x2 y2 to class_name x1 y1 x2 y2 ?

**Comment by ZhAnGToNG1** [comment]
What dataset do you use?

**Comment by ZhAnGToNG1** [comment]
There is indeed no transferring function. It needs to prepare the ground-truth of your own dataset by yourself.

**Comment by Ismaildata** [comment]
i use NWPU VHR dataset sir.

**Comment by ZhAnGToNG1** [comment]
This is just a simple correspondence between class_name and class_index. I think it is not hard for you.  😊

**Comment by Ismaildata** [comment]
Yes dear, and when executing demo when can i found my result images ?
