### ISSUE TITLE
number of epochs used to obtain this accuracy ?

### ISSUE THREAD

**Issue by Ismaildata** [ZhAnGToNG1/MSFC-Net#11]
please , can you tell me epochs  number used to obtain 80% of accuracy in DOTA dataset and which batch size did you used ?

**Comment by ZhAnGToNG1** [comment]
Please read the related paper [https://ieeexplore.ieee.org/abstract/document/9535169](url). There is implementation details in the paper.

**Comment by ZhAnGToNG1** [comment]
Generally, the best model will be obtained after 40~50 epoch. Then, it needs to constantly test to find the best model.
