### ISSUE TITLE
Best of model 10000000000.0 meaning ?

### ISSUE THREAD

**Issue by Ismaildata** [ZhAnGToNG1/MSFC-Net#12]
perform validation
ctdet/msfcnet |################################| val: [5][259/260]|Tot: 0:00:35 |ETA: 0:00:01 |loss 3.3747 |hm_loss 2.2158 |wh_loss 5.0119 |iou_loss 0.4111 |off_loss 0.2466 
{'loss': 3.374723135966521, 'hm_loss': 2.2158370967094716, 'wh_loss': 5.011867908560313, 'iou_loss': 0.41113565747554487, 'off_loss': 0.24656356504330268, 'time': 0.5833333333333334}
Loss of model: 3.374723135966521
Best of model 10000000000.0

please what is the meaning of this values : 
Best of model 10000000000.0 ?

**Comment by ZhAnGToNG1** [comment]
Ensure getting a lower loss value than the initial loss value **10000000000.0**. It aims to obtain the best model according to the minimum loss value.

**Comment by Cherich-GL** [comment]
> perform validation ctdet/msfcnet |################################| val: [5][259/260]|Tot: 0:00:35 |ETA: 0:00:01 |loss 3.3747 |hm_loss 2.2158 |wh_loss 5.0119 |iou_loss 0.4111 |off_loss 0.2466 {'loss': 3.374723135966521, 'hm_loss': 2.2158370967094716, 'wh_loss': 5.011867908560313, 'iou_loss': 0.41113565747554487, 'off_loss': 0.24656356504330268, 'time': 0.5833333333333334} Loss of model: 3.374723135966521 Best of model 10000000000.0
> 
> please what is the meaning of this values : Best of model 10000000000.0 ?
