### ISSUE TITLE
is multiscale preprocessing mandatory to get good results?

### ISSUE THREAD

**Issue by TerrafYassin** [ZhAnGToNG1/MSFC-Net#15]
please is multiscale preprocessing mandatory to get good results?
because scale images allows to increase the number of images and suddenly bombard the RAM, I also have a question is that multi scale applied during training must also apply if I want to make a demo with large scale image?

**Comment by ZhAnGToNG1** [comment]
Yes. Multi-scale training and testing can bring better results.
Multiscale training and multiscale testing are independent.

- Multi-scale training : use the code https://github.com/ZhAnGToNG1/MSFC-Net/blob/eb378219563f178113b3f9a2590ade3f224a8c3e/dota_dekit/ImgSplit_multi_process.py to prepare original dataset.
- Multi-scale testing: achieve it by using [https://github.com/ZhAnGToNG1/MSFC-Net/blob/eb378219563f178113b3f9a2590ade3f224a8c3e/src/lib/detectors/base_detector.py#L69](url).
- You can only use multi-scale testing, not multi-scale training.

**Comment by TerrafYassin** [comment]
thank you so much , so even NWPU VHR dataset i need to use  multi-scale training and testing and resize all images to 512 *512 ?

**Comment by TerrafYassin** [comment]
and can you please give me FPS obtained when use multi scale testing because i think it will make  the detection more slower No ?

**Comment by ZhAnGToNG1** [comment]
Yes. it is necessary to split original images into 512 *512 in this code. But, multi-scale training and testing is optional.
Noting that FPS depends on hardware.  In our experimental environment, the inference time (ms) have been displayed on the  **TABLE VIII** of this paper.

**Comment by TerrafYassin** [comment]
so , your model can detect object in large scale image , no need to do  multi-scaling before use detection network ?

**Comment by ZhAnGToNG1** [comment]
yes

**Comment by TerrafYassin** [comment]
thank you i will test it

**Comment by TerrafYassin** [comment]
please what mean number 1 in  split.splitdata(1) ?
