### ISSUE TITLE
Multi-scale splitting in NWPU VHR dataset 

### ISSUE THREAD

**Issue by TerrafYassin** [ZhAnGToNG1/MSFC-Net#18]
please dear ,  in NWPU VHR dataset i have this format class_name , x, y , w , h but dotadevkit fromat :  x1 y1 x2 y2 x3 y3 x4 y4 category difficult , my question dear how can i  resize the training set of  NWPU VHR into multiple scales, ×1.2,
×1, and ×0.4, and crop them into 512 × 512 subimages,

**Comment by ZhAnGToNG1** [comment]
Use dotadevkit

**Comment by TerrafYassin** [comment]
but dotadevkit fromat : x1 y1 x2 y2 x3 y3 x4 y4 category difficult

**Comment by TerrafYassin** [comment]
can you help me please ?
