### ISSUE TITLE
mAP not appear during model training 

### ISSUE THREAD

**Issue by Ismaildata** [ZhAnGToNG1/MSFC-Net#5]
Thank you for this work, I want to know why the mAP value does not calculate during training, how can I have mAP metric after training my model?

**Comment by ZhAnGToNG1** [comment]
Due to the characteristic of large resolution of DOTA, we don't add the function about calculating mAP during model training. You can test the trained model, and then refer to [https://github.com/ZhAnGToNG1/MSFC-Net/blob/master/README.md](url): **Evaluation** to calculate mAP metric.

**Comment by TerrafYassin** [comment]
Thank you

**Comment by Ismaildata** [comment]
Thank you
