### ISSUE TITLE
test.py file not found

### ISSUE THREAD

**Issue by Ismaildata** [ZhAnGToNG1/MSFC-Net#8]
python test.py ctdet --exp_id test_dior --test_dir `your data path`
please when can i find test.py file to test my model ?

**Comment by ZhAnGToNG1** [comment]
See [https://github.com/ZhAnGToNG1/MSFC-Net/blob/master/src/test_dota.py](url) or [https://github.com/ZhAnGToNG1/MSFC-Net/blob/master/src/test_dota.py](url).
